// Mock events for local dev until Dev 1's 1.6 (GET /api/events) ships.
// Shape matches the API schema in STATE.md exactly so swap is a no-op.
export const SEED_EVENTS = [
  {
    id: 1,
    title: 'Saturday arvo BBQ',
    description: 'BYO everything, we supply the onions. Newcomers welcome.',
    event_type: 'social',
    start_time: '2026-05-30T12:00:00',
    end_time: '2026-05-30T15:00:00',
    host: { id: 1, name: 'Priya' },
    location: { id: 1, name: 'Flagstaff Gardens BBQ', type: 'bbq' },
    attendee_count: 7,
    max_attendees: 20,
    user_rsvp: null,
  },
  {
    id: 2,
    title: 'Tomato seedling planting',
    description: 'Hands-on session at CERES. Tools and gloves provided.',
    event_type: 'plant_learn',
    start_time: '2026-05-31T10:00:00',
    end_time: '2026-05-31T12:00:00',
    host: { id: 2, name: 'Marco' },
    location: { id: 6, name: 'CERES Community Garden', type: 'garden_bed' },
    attendee_count: 4,
    max_attendees: 12,
    user_rsvp: 'going',
  },
  {
    id: 3,
    title: 'Filipino night at FareShare',
    description: 'Cooking adobo and pancit together. All ingredients covered.',
    event_type: 'cook_share',
    start_time: '2026-06-02T18:00:00',
    end_time: '2026-06-02T20:30:00',
    host: { id: 3, name: 'Joanna' },
    location: { id: 11, name: 'FareShare Kitchen', type: 'community_kitchen' },
    attendee_count: 12,
    max_attendees: 15,
    user_rsvp: null,
  },
  {
    id: 4,
    title: 'Bike repair pop-up',
    description: 'Bring your broken bike. Volunteer mechanics on hand.',
    event_type: 'fix_flow',
    start_time: '2026-06-05T14:00:00',
    end_time: '2026-06-05T17:00:00',
    host: { id: 4, name: 'Sam' },
    location: { id: 5, name: 'Edinburgh Gardens BBQ', type: 'bbq' },
    attendee_count: 2,
    max_attendees: null,
    user_rsvp: null,
  },
]
